### ISSUE TITLE
lba2 has become open source

### ISSUE THREAD

**Issue by seocamo** [LBALab/lba2remake#675]
**Is your feature request related to a problem? Please describe.**
lba2 has get a open source release, at [lba2-classic](https://github.com/2point21/lba2-classic), would be nice the assets could come from this, so we don't need to find our 31 year old CD to get it running

**Describe the solution you'd like**
import assets

**Comment by xesf** [comment]
Hi @seocamo,

Although the LBA series has been open sourced, the assets are still **copyrighted** and **not re-distributed**.

I suggest you to buy the game on popular platforms like GoG, Steam, Itch which will support the Studio 2.21 behind creating the new LBA series game.

Here are the links to buy the games:
https://itch.io/s/61876/adeline-software-collection
https://www.gog.com/games?developers=adeline-software-international 
https://store.steampowered.com/search/?publisher=%5B2.21%5D
